class_name AwkyMessages
extends Resource

@export var messages = {
	0 : [0, "hiiiii!"],
	1 : [1, "ahhhhhh i missed my bus to work this morning and then it started raining and I didn’t bring an umbrella so i was just kinda of huddling under the little ledge thing they have in front of the conveniences store door but anyways I was soaked when the next bus arrived and it was late too cuz ig the rain worsen the traffic more than usual I also dropped my phone in a puddle it seems to be working fin so far but im still kinda worried but yeah anyways work wasn’t so fun cuz i was wet and soaking the whole time and i had to work past hours too to make up for being late and by the time I got back the pastry store was sold out of strawberry cheesecakes but yeah"],
	2 : [2, "I like watching tv shows"],
	3 : [3, "i’m studying to be an accountant tho I don’t have certification yet so i just do really basic stuff rn as an assistant like data entry and handling emails when I do real work my boss is always hovering my shoulder to make sure I did it right you need like two years of work experience to qualify and i also haven’t taken the exam yet so gotta stay on that grind"],
	4 : [4, "yeahhhhhh that would just make all of this worse, tho i showered immediately when i got back and i was pretty much dry by then but anyways uhhhhh how was your day?"],
	5 : [5, "i just got into this series call prism dreamers it’s about this kid who finds a magic rock that lets him enter other people dreams while they are sleeping while playing around with it he finds out that his teacher is secretly an alien. the aliens are trying to kill Carl cuz the magic rock is kinda stuck to the back of his head and they want it back ig oh btw carl is the name of the main character so yeah anyways he tries to go on the run with his friend jassy who really likes occult stuff so they want to tag along for fun jassy;s my favorite they are so badass and they end up learning magic to help ward off the aliens but yeah theyre main goal is to find the prism dreamers headquarters who supposed to know how to take off the rock although i have a theory that the place is actually run by aliens trying to gather all the people who have their rocks also because they call people like Carl incubators, so like maybe the rocks are actually eggs and they need people to help them like hatch the egg????? so like that’s how to recollect the rocks once hey come to term or smth so anyways the show is so cool you should watch it"],
	6 : [6, "you won’t regert it I promise especially once jassy stqarts learning magic and they meet wellie she’s lowkey crazy but like in a good way trust me her and jassy together is always such a riot they really need to interact moreeeeeeee but then her brother died so ig wellie’s too busy dealign with that."],
	7 : [7, "oh shoot, sorry spoilers! :("],
	8 : [8, "yeah my boss is pretty strict to but she was nice enough to hire me to begin with so ig i shouldn’t complain!"]
}
